// Regenerates src/generated/** from GeoNames.
//
//   yarn generate && yarn build
//
// Source: https://www.geonames.org/ - CC-BY 4.0, attribution only, no
// share-alike. Requires Node 18+ (global fetch) and the `unzip` binary.

import { execFileSync } from "node:child_process";
import { existsSync } from "node:fs";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";

import {
  cityOverrides,
  countryOverrides,
  stateOverrides,
} from "./overrides.js";

/**
 * "ALL" is the right default: cities are ONE LAZY CHUNK PER COUNTRY, so a user
 * who picks Pakistan downloads Pakistan's 20 KB and nothing else - identical
 * whether this ships 5 countries or 250. Narrow to an array of ISO2 codes only
 * to deliberately restrict the country dropdown.
 */
const SUPPORTED = "ALL";

/** cities1000 = 170,978 places. cities5000 / cities15000 are smaller. */
const CITY_SET = "cities1000";

const BASE = "https://download.geonames.org/export/dump";
const OUT = "src/generated";

async function download(file) {
  const cached = `.tmp/${file}`;
  if (existsSync(cached)) return cached;

  console.log(`downloading ${file}…`);
  const response = await fetch(`${BASE}/${file}`);
  if (!response.ok) throw new Error(`${file}: HTTP ${response.status}`);

  await mkdir(".tmp", { recursive: true });
  await writeFile(cached, Buffer.from(await response.arrayBuffer()));
  return cached;
}

/** Tab-separated, `#` comments. */
function parseTsv(text) {
  return text
    .split("\n")
    .filter((line) => line && !line.startsWith("#"))
    .map((line) => line.split("\t"));
}

const banner = "// GENERATED by scripts/generate.mjs - do not edit by hand.\n";
const byName = (a, b) => a.name.localeCompare(b.name);

/**
 * Applies a display-name override while preserving searchability: the upstream
 * name is folded into `aliases` automatically, so a rename can never make a
 * place unfindable.
 */
function applyOverride(record, override) {
  if (!override) return record;

  const aliases = new Set(override.aliases ?? []);
  if (override.name && override.name !== record.name) aliases.add(record.name);

  return {
    ...record,
    ...(override.name ? { name: override.name } : {}),
    ...(aliases.size > 0 ? { aliases: [...aliases] } : {}),
  };
}

const countryFile = await download("countryInfo.txt");
const admin1File = await download("admin1CodesASCII.txt");
const cityZip = await download(`${CITY_SET}.zip`);

const cityText = execFileSync("unzip", ["-p", cityZip, `${CITY_SET}.txt`], {
  encoding: "utf8",
  maxBuffer: 512 * 1024 * 1024,
});

// countryInfo.txt: 0 ISO, 4 Country, 10 CurrencyCode, 12 Phone
const allCountries = parseTsv(await readFile(countryFile, "utf8")).map((r) => ({
  code: r[0],
  name: r[4],
  phoneCode: String(r[12] ?? "").replace(/^\+/, ""),
  currency: r[10] ?? "",
}));

const wanted = SUPPORTED === "ALL" ? allCountries.map((c) => c.code) : SUPPORTED;

const countries = wanted
  .map((code) => {
    const match = allCountries.find((c) => c.code === code);
    if (!match) throw new Error(`unknown country code in SUPPORTED: ${code}`);
    return applyOverride(match, countryOverrides[code]);
  })
  .sort(byName);

const included = new Set(countries.map((c) => c.code));

// An override that matches nothing is almost always a typo or a missing
// SUPPORTED entry. Silence would be the worst outcome.
for (const code of Object.keys(countryOverrides)) {
  if (!included.has(code)) {
    console.warn(`[overrides] countryOverrides.${code} unused - not in SUPPORTED`);
  }
}

// admin1CodesASCII.txt: 0 "CC.ADMIN1", 1 name
const statesByCountry = {};
for (const row of parseTsv(await readFile(admin1File, "utf8"))) {
  const [countryCode, stateCode] = row[0].split(".");
  if (!included.has(countryCode) || !stateCode) continue;

  (statesByCountry[countryCode] ??= []).push(
    applyOverride({ code: stateCode, name: row[1] }, stateOverrides[row[0]]),
  );
}

// cities: 0 id, 1 name, 8 country, 10 admin1, 14 population
const citiesByCountry = {};
for (const row of parseTsv(cityText)) {
  const countryCode = row[8];
  const stateCode = row[10];
  if (!included.has(countryCode) || !stateCode) continue;

  const index = (citiesByCountry[countryCode] ??= {});
  const id = Number(row[0]);

  (index[stateCode] ??= []).push(
    applyOverride(
      { id, name: row[1], pop: Number(row[14]) || 0 },
      cityOverrides[id],
    ),
  );
}

await rm(OUT, { recursive: true, force: true });
await mkdir(`${OUT}/states`, { recursive: true });
await mkdir(`${OUT}/cities`, { recursive: true });

await writeFile(
  `${OUT}/countries.ts`,
  `${banner}import type { Country } from "../types.js";\n\nconst countries: Country[] = ${JSON.stringify(countries)};\n\nexport default countries;\n`,
);

for (const country of countries) {
  const states = (statesByCountry[country.code] ?? []).sort(byName);
  const rawIndex = citiesByCountry[country.code] ?? {};

  // Sorted by population DESC, then `pop` is dropped - it only existed to drive
  // the sort. Makes the picker's default list the biggest cities, not the ones
  // starting with "A".
  const cityIndex = {};
  let cityCount = 0;

  for (const [stateCode, list] of Object.entries(rawIndex)) {
    const sorted = list
      .sort((a, b) => b.pop - a.pop)
      .map(({ id, name, aliases }) =>
        aliases ? { id, name, aliases } : { id, name },
      );

    cityIndex[stateCode] = sorted;
    cityCount += sorted.length;
  }

  await writeFile(
    `${OUT}/states/${country.code}.ts`,
    `${banner}import type { State } from "../../types.js";\n\nconst states: State[] = ${JSON.stringify(states)};\n\nexport default states;\n`,
  );
  await writeFile(
    `${OUT}/cities/${country.code}.ts`,
    `${banner}import type { CityIndex } from "../../types.js";\n\nconst cities: CityIndex = ${JSON.stringify(cityIndex)};\n\nexport default cities;\n`,
  );
}

// Explicit loader maps - bundlers can only code-split static specifiers.
const entries = (kind) =>
  countries
    .map(
      (c) =>
        `  ${c.code}: () => import("./generated/${kind}/${c.code}.js").then((m) => m.default),`,
    )
    .join("\n");

await writeFile(
  "src/loaders.ts",
  `${banner}import type { CityIndex, State } from "./types.js";

export const stateLoaders: Record<string, () => Promise<State[]>> = {
${entries("states")}
};

export const cityLoaders: Record<string, () => Promise<CityIndex>> = {
${entries("cities")}
};
`,
);

console.log(`done - ${countries.length} countries`);
